### ISSUE TITLE
Show controls 💅

### ISSUE THREAD

**Issue by zzarcon** [devlucky/react-audio-vis#10]
Do we want the users to optionally show the audio controls? (play/pause, time, volume, etc)

In that case, I guess we want to build a custom ones?

**Comment by majames** [comment]
I'm thinking that this would be a nice to have in the long term. 

Initially, I was thinking the MVP would just focus on producing different visualisations from audio data (regardless of the source). Consumers could use native browser controls or use their own, our library is just concerned with visualising dem signals 🎶 🎶 🎶 🎶

**Comment by zzarcon** [comment]
Agreed! Maybe we can create a milestone here and define which features we want for the 1.0?
