### ISSUE TITLE
Project name

### ISSUE THREAD

**Issue by zzarcon** [devlucky/react-audio-vis#2]
I think we should find a fancier name for the project, some proposals (Already checked and they are free on npm:

* **react-synthesizer**
* **react-fancy-audio**
* **react-turtle**
* **react-headphones**
* **react-micdrop**
* **audio-cowboy**

### Questions:

* Do we want to prefix the package with **react**
* Do we want to include **audio** in the name?
* Should we chose a random but cool name like ```casper```, ```kiwi```?

**Comment by majames** [comment]
hahaha love it!

My favourites are either *react-synthesizer* or *react-micdrop*.

I think we should keep the *react* prefix as it is a convention that most react libraries use.

**Comment by zzarcon** [comment]
Yeah! I also think makes the lib easy to discover :shipit:

**Comment by zzarcon** [comment]
Alright! After a year deciding the name (:trollface:) Im going to change the name to **react-micdrop**

**Comment by zzarcon** [comment]
🚀 https://www.npmjs.com/package/react-micdrop 🚀

**Comment by majames** [comment]
Worth the wait!

![its-alive](https://user-images.githubusercontent.com/7553458/43690860-62b11c36-98c6-11e8-950f-dd64ebf26d9d.gif)
