### ISSUE TITLE
Move project into an Org

### ISSUE THREAD

**Issue by zzarcon** [devlucky/react-audio-vis#8]
Which are your thoughts about moving the project into an org?

We can create a new one or use the [**Devlucky**](https://github.com/devlucky/) one in which we already have a couple of famous projects + accounts in [Twitter](https://twitter.com/devluckyness) (195 followers) and [Medium](https://medium.com/@devlucky) (480 followers) and I think we can reach more people 🎸

**Comment by majames** [comment]
If you guys are happy for me to jump in Devlucky I'm keen 😄

**Comment by majames** [comment]
🏢 devlucky in da house
